### ISSUE TITLE
godoctor rename issue

### ISSUE THREAD

**Issue by microamp** [godoctor/godoctor#33]
Hi, 

Rename stops working after a variable has been renamed to a single letter.

More details here: https://github.com/microamp/godoctor.el/pull/10#issuecomment-263234788

Switching between `num` and `number` works. But as soon as it's renamed to a single letter, say `n`, the next run of rename leads to the following error.

```
Defaulting to package scope github.com/microamp/godoctor-example for refactoring (provide an explicit scope to change this)
main.go:6:3: Error: Please select an identifier to rename. (Selected node: *ast.AssignStmt)
```

The issue is reproducible in Emacs. I'd like to know if it's reproducible in Vim too. Please ping me if you need more info. Cheers!

**Comment by roberthorn** [comment]
I'm not able to reproduce this in Vim. Assuming the following code:
```
package main

import "fmt"

func main() {
        num := 1
        fmt.Println(num)
}
```
doing `num -> n -> num` works every time.

Basically it's having trouble finding the variable from your selection.

Messing with godoctor, it seems that the `-pos offset,len` style isn't very consistent, I'm able to reproduce the problem with variable `n` with `godoctor -file main.go -pos 44,1 rename num`. 

I'm pretty sure the Vim plugin uses the `-pos startrow,startcol:endrow,endcol` format, which if you try godoctor with `godoctor -file main.go -pos 6,5:6,5 rename num`, it'll will work. Be wary of tabs/spaces though.

@rdallman @joverbey sound right?

**Comment by rdallman** [comment]
thanks for debugging and raising issue. should we require the `startrow,startcol:endrow,endcol` syntax in the api to avoid such issues in the future?

**Comment by microamp** [comment]
Thanks I'll try the longer format as suggested. Will report back!

**Comment by microamp** [comment]
The suggested format works much better.
```
-pos startrow,startcol:endrow,endcol
```

And now I have [applied the change to the Emacs package](https://github.com/microamp/godoctor.el/pull/12).

@roberthorn @rdallman Thanks for helping me sort this out.
