### ISSUE TITLE
Move away from version numbers?

### ISSUE THREAD

**Issue by joverbey** [godoctor/godoctor#34]
@rdallman @roberthorn We've been giving version numbers to Go Doctor releases (we're at 0.3 now), but I'm wondering if we should move away from that.  Basically, every time we bump the version number, I have to tag a commit, rebuild the documentation, and update the web site.  Is there any advantage to that?  As an alternative, we could just pull features into master one by one, and only update the documentation when it actually changes (same with the web site).

What do you think?  If we move away from version numbers, can we somehow get "godoctor --help" to show the SHA-1 for the commit it was built from?

**Comment by roberthorn** [comment]
Given the sad state of package management in Go, I guess strict versioning doesn't really matter? Especially in the pre-1.0 stages. But having a semantic versioning scheme may be useful if some package management tool gets accepted in the future. 

Dave Cheney gives his opinion on versioning here: https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

Maybe there's a better way to automate the documentation and such?

**Comment by rdallman** [comment]
Perhaps we should remove any references to the version on the docs and/or web site and those are always assumed to be latest (if web and git are in docs then it should be easy enough to track updates)? It may also be entirely possible to use the `/releases/latest` [link](https://help.github.com/articles/linking-to-releases/) and parse that, which seems not working properly for us as all our releases seem to be 'pre-releases' and for some reason aren't fully qualified enough to be latest. wat. Using commit sha would create the same issue where every commit would have to update the docs, no?

I've a release script laying around for doing some of this stuff like bumping and tagging versions, we may be able to extend it easily enough to any further uses. I will make a note to fiddle with it and make a release branch we can just use with CI to do releases for us.

I think there's some value in having separate versions from whatever is tip on master as it at least gives the illusion that we have done extensive testing on a commit that also has a tag and we think it's okay to use (no intermediary commits or regressions known, etc).. For us, over time it seems like it will mostly be saying that x version is updated to support version 1.x of Go (types package and such) and it's useful to be able to have that broken out in releases if for some reason people are e.g. stuck on go 1.4 they can keep using an older version (bad example, 1.4 may already be broke over vendoring but idk :)

**Comment by joverbey** [comment]
Thanks for the comments.  I agree it makes sense to stick with tagged versions.

It's really not difficult to tag and update.  Not sure why I was whining about that.  I added instructions to godoctor/INTERNALS and www/README to make it easier next time (won't forget steps).
