### ISSUE TITLE
godoc refactoring adds unnecessary comment for types and ignores value declarations

### ISSUE THREAD

**Issue by roberthorn** [godoctor/godoctor#37]
The godoc refactoring currently adds a godoc comment to exported functions and types even when a valid godoc comment exists. This seems to be an issue where we're not properly configuring the AST parser to parse comments instead of the logic of the actual refactoring. 

I've added a branch `bug/godoc-adds-comment-when-existing` with a failing test the demonstrates the issue.

**Comment by roberthorn** [comment]
The original issue is actually how we're checking for the godoc comment. Currently checking the `ast.TypeSpec` doc field for an existing comment, which is only present with declaration groups. Have to use the doc field in `ast.GenDecl` in the case of a non-group declaration.

This also means we weren't properly checking for godoc comments for value declarations (constants and vars). 

Question is: for group declarations, do we want to comment on the declaration or each specified name? It's valid to have a single godoc comment for the entire group or for each exported declaration.

Example, given this:
```go
const (
    A = "foo"
    B = "bar"
)
```
Do we want this:
```go
// TODO: NEED COMMENT INFO
const (
    A = "foo"
    B = "bar"
)
```

Or this:
```go
const (
    // A TODO: NEED COMMENT INFO
    A = "foo"
    // B TODO: NEED COMMENT INFO
    B = "bar"
)
```
@joverbey

**Comment by joverbey** [comment]
@roberthorn Whatever you think; your call.  Which one do people want most of the time?  Worst case, we could add a boolean flag to the refactoring to toggle the behavior, but I'd prefer to just do something reasonable by default.

I was trying to use, as an example, https://golang.org/pkg/go/token/#Token - source at  https://golang.org/src/go/token/token.go#L13 - but I probably need to look at some more godoc to form an opinion
