### ISSUE TITLE
Can't rename struct fields

### ISSUE THREAD

**Issue by jredville** [godoctor/godoctor#39]
```golang
type Foo struct {
  messages []string
}

func NewFoo() *Foo {
  return &Foo{
    messages: []string{},
  }
}
```
Given the above, if my cursor is on either of the messages lines, and I invoke godoctor rename to rename `messages` to `Messages` for example, I get an error: `Error: Please select an identifier to rename. (Selected node: *ast.KeyValueExpr)` (the last part varies). I'd like to be able to rename struct fields as easily as identifiers

**Comment by roberthorn** [comment]
We do support renaming struct fields. I'm able to rename the `messages` field in your example above.

Just to be clear, you're placing your cursor on the actual identifier or visually selecting it, right? It's not enough to just be on the line of the identifier. I'm also assuming you're using our vim plugin, so correct me if I'm wrong.

**Comment by jredville** [comment]
Hm, I'm using an emacs plugin. I'll look into it and see if there is a bug in the plugin, I should have checked that first.

Jim

**Comment by roberthorn** [comment]
@jredville have you had any luck figuring out if it was a bug with your editor plugin? I'm going to close this issue since it seems this isn't a bug in godoctor.
