### ISSUE TITLE
Function Extract failure

### ISSUE THREAD

**Issue by cbehopkins** [godoctor/godoctor#42]
Hi
Hopefully this isn't user error, but I've found a pattern I use in some of my code that seems to really upset the extract feature.  In my tiddly test case I see an even weirder error where any attempt to extract anything says: "Error: invalid selection: An empty block cannot be extracted"
But  when this pattern exists in my larger codebases the Extract function succeeds, but creates invalid variables that clash with the existing namespace.
Anyway, here's the noddy code:
`package main

import (
  "fmt"
  "strings"
)

func main() {
  inputString := "bob"
  listOfWork := []string{"a", "b", "c"}
  var workDone bool

  // This for loop can't seem to be extracted with any success
  for _, wrk := range listOfWork {
    if strings.Contains(inputString, wrk) {
      workDone = true
      inputString = strings.Replace(inputString, wrk, ".", -1)
    }
  }

  if workDone {
    fmt.Println("done something")
  }
}
`

**Comment by roberthorn** [comment]
Could you give some info on how you're using the tool? Are you using the vim or emacs plugin or using the tool directly? Also, the "empty block" error from your example and the tool successfully extracting, but creating variable conflicts are two very different issues. Could you give more context or better replicate the variable conflict issue you're seeing?

FWIW, I was able to take your example above and extract the loop, giving the resulting (runnable) code:

```go
package main

import (
	"fmt"
	"strings"
)

func main() {
	inputString := "bob"
	listOfWork := []string{"a", "b", "c"}
	var workDone bool

	workDone = doWork(inputString, listOfWork)

	if workDone {
		fmt.Println("done something")
	}
}

func doWork(inputString string, listOfWork []string) bool {
	var workDone bool
	for _, wrk := range listOfWork {
		if strings.Contains(inputString, wrk) {
			workDone = true
			inputString = strings.Replace(inputString, wrk, ".", -1)
		}
	}
	return workDone
}
```

**Comment by cbehopkins** [comment]
My apologies, I should know better than to write a bug report with insufficient coffee! (the empty block error was me being stupid, please ignore that, working now). I use vim 8.0.5 & 7.4.576 depending on which machine I'm on. Same problem on both.
Seems like I had simplified my test case too much, There are 2 additional things that seem to be required for this to happen:
* The for loop needs to be in a method
* That returns the string as well as the work done

```
package main

import (
	"fmt"
	"strings"
)

type Dummy struct{}

func main() {
	inputString := "bob"
	listOfWork := []string{"a", "b", "c"}
	var workDone bool
	var dum Dummy
	inputString, workDone = dum.work(listOfWork, inputString)

	if workDone {
		fmt.Println("done something", inputString)
	}
}

func (dm Dummy) work(listOfWork []string, inputString string) (string, bool) {
	var workDone bool
	// This for loop can't seem to be extracted with any success
	for _, wrk := range listOfWork {
		for strings.Contains(inputString, wrk) {
			inputString = strings.Replace(inputString, wrk, ".", -1)
			workDone = true
		}
	}

	return inputString, workDone
}

```
With the new test case, visually selecting the for loop and typing 'Refactor extract bob' I get:
```
tst.go|| Error: Completing the transformation will introduce the following error: tst.go:31:6: inputString redeclared in this block
tst.go|| previous declaration at tst.go:30:21
tst.go|31 col 6 error| Error: inputString redeclared in this block
tst.go|30 col 21 error| Error: 	other declaration of inputString
```
Sorry, again.

**Comment by cbehopkins** [comment]
So I've done some more experimentation:
The critical things to make this happen seem to be:
* The code to be extracted is in a method
* The code to be extracted modifies one of the input terms that will later be read
Modified Example below:
```
package main

import (
	"fmt"
	"strings"
)

type Dummy struct{}

func main() {
	inputString := "bob"
	listOfWork := []string{"a", "b", "c"}
	var dm Dummy
	inputString = dm.work(inputString, listOfWork)
	fmt.Println("done something", inputString)
}

func (dm Dummy) work(tmp string, listOfWork []string) (outputString string) {
	inputString := tmp + " Suffix"
	wrkDone := false
	// This if can't seem to be extracted with any success
	if !wrkDone && strings.Contains(inputString, "Suffix") {
		wrkDone = true
	}
	if wrkDone {
		fmt.Println("Got something", inputString)
	}
	outputString = "steve"
	return
}
```

**Comment by cbehopkins** [comment]
I'm not sure if you would rather this were raised as a separate issue, but during my experimentation I discovered a situation where the extract function can produce incorrect code.
If you do a similar pattern where in the code you extract you modify a bool, then unless in that code you explicitly read the bool first then the current value of the bool is ignored. 
```
package main

import (
	"fmt"
	"strings"
)

func main() {
	inputString := "bob"
	missingSuffix := true
	// If you extract this if
	// then it ignores the current value of missingSuffix
	if strings.Contains(inputString, "Suffix") {
		missingSuffix = false
	}

	fmt.Print("string:", inputString)
	if missingSuffix {
		fmt.Println(" is missing Suffix")
	} else {
		fmt.Println(" contains Suffix")
	}
}
```
Extracting the commented on if, gives you:
```
	missingSuffix = fred(inputString)


func fred(inputString string) bool {
	var missingSuffix bool
	if strings.Contains(inputString, "Suffix") {
		missingSuffix = false
	}
	return missingSuffix
}
```
Which will give you the incorrect result.

**Comment by roberthorn** [comment]
Awesome, these are some good test cases. Will get to these asap

**Comment by joverbey** [comment]
Thanks for reporting these!  These are great test cases.  Sorry they broke for you!

The first one is an easy fix.  In `analyzeVars`, we modify the set of local variables when there is a receiver, but (copy and paste error?) it's operating on the wrong set.  I'm surprised that this slipped through all of our test cases.  It should be:
```go
if recvNode := r.stmtRange.enclosingFunc.Recv; recvNode != nil {
        ...
        locals = difference(locals, []*types.Var{recv}) // was returns, not locals, which is incorrect
}
```

I created Issue #43 for the second one, since it's a bit trickier and might take a little longer to fix/qualify.

**Comment by cbehopkins** [comment]
Please don't apologise, thanks for making a great tool. Very much appreciated!
