### ISSUE TITLE
Is this tool actively mantained ?

### ISSUE THREAD

**Issue by vladbarosan** [godoctor/godoctor#49]
Hi, we are planning to use this tool but it seems there is not much dev on it on fixing issues or new features. 

So my question : is this repo actively mantained and is there a roadmap for it ?

**Comment by rdallman** [comment]
Hi @vladbarosan - there is not an active development team working on the project at the moment, however there's at least a couple of us keeping tabs on the project, reviewing PRs and keeping it working with recent go releases - I use it often in my own dev environment. I'm not aware of any roadmap, we are open to new refactorings / fixes / features though and happy to discuss.
