### ISSUE TITLE
it seems like go module cannot work with "Extract to function" in vscode

### ISSUE THREAD

**Issue by Bashikuaidi** [godoctor/godoctor#54]
i'v set GO111MODULE="on", but when i use "extract to function", it will has these errors:
Defaulting to package scope ${path} for refactoring (provide an explicit scope to change this) ../../../../../github.com/gin-gonic/gin/binding/default_validator.go:11:2: Error: could not import github.com/go-playground/validator/v10 (cannot find package "github.com/go-playground/validator/v10" in any of: /usr/local/go/src/github.com/go-playground/validator/v10 (from $GOROOT) /home/${name}/go/src/github.com/go-playground/validator/v10 (from $GOPATH)).

why it didn't find module in ${GOPATH}/pkg/mod?

**Comment by moshemarciano** [comment]
still an issue.. @joverbey 
blocking vscode extract to function feature
https://github.com/microsoft/vscode-go/issues/3040

**Comment by rdallman** [comment]
making progress here: https://github.com/godoctor/godoctor/pull/52 but no guarantees just yet :)
